server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
#  flyway:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo_db}
#    user: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#    locations: [ 'classpath:db/migration/dev' ]

logging:
  level:
    org.hibernate.jpa: info
    org.hibernate.sql: info
    org.hibernate.type: info
